// trm_test.go — Validates Go MambaTRM against Python reference outputs.
//
// Loads trm_reference.json (generated by trm_export.py) and trm_weights.bin,
// then verifies that the Go implementation produces matching scores within
// a tight tolerance. Tests are skipped if binary files don't exist (CI-safe).
package main

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// trmReferenceData mirrors the JSON structure from trm_export.py.
type trmReferenceData struct {
	Config               map[string]interface{} `json:"config"`
	TestQuery            []float64              `json:"test_query"`
	CandidateIndices     []int                  `json:"candidate_indices"`
	NCandidates          int                    `json:"n_candidates"`
	ScoresNoLightcone    []float64              `json:"scores_no_lightcone"`
	ContextNoLightcone   []float64              `json:"context_no_lightcone"`
	StatesNoLightcone    [][][]float64          `json:"states_no_lightcone"`
	SecondEvent          []float64              `json:"second_event"`
	ScoresWithLightcone  []float64              `json:"scores_with_lightcone"`
	ContextWithLightcone []float64              `json:"context_with_lightcone"`
	StatesWithLightcone  [][][]float64          `json:"states_with_lightcone"`
}

// trmTestPaths returns paths to the test data files.
func trmTestPaths() (weightsPath, referencePath, embeddingsPath string) {
	dir := filepath.Join("autoresearch")
	return filepath.Join(dir, "trm_weights.bin"),
		filepath.Join(dir, "trm_reference.json"),
		filepath.Join(dir, "trm_embeddings.bin")
}

// skipIfMissing skips the test if any of the given files don't exist.
func skipIfMissing(t *testing.T, paths ...string) {
	t.Helper()
	for _, p := range paths {
		if _, err := os.Stat(p); os.IsNotExist(err) {
			t.Skipf("skipping: %s not found (run trm_export.py to generate)", p)
		}
	}
}

// f64ToF32 converts a float64 slice to float32.
func f64ToF32(in []float64) []float32 {
	out := make([]float32, len(in))
	for i, v := range in {
		out[i] = float32(v)
	}
	return out
}

// f64ToF32_2D converts a 2D float64 slice to 2D float32.
func f64ToF32_2D(in [][]float64) [][]float32 {
	out := make([][]float32, len(in))
	for i := range in {
		out[i] = f64ToF32(in[i])
	}
	return out
}

// maxAbsDiff returns the maximum absolute difference between two float32 slices.
func maxAbsDiff(a, b []float32) float64 {
	if len(a) != len(b) {
		return math.Inf(1)
	}
	var maxDiff float64
	for i := range a {
		diff := math.Abs(float64(a[i]) - float64(b[i]))
		if diff > maxDiff {
			maxDiff = diff
		}
	}
	return maxDiff
}

func TestTRMLoadWeights(t *testing.T) {
	weightsPath, _, _ := trmTestPaths()
	skipIfMissing(t, weightsPath)

	trm, err := LoadTRM(weightsPath)
	if err != nil {
		t.Fatalf("LoadTRM: %v", err)
	}
	if trm.Config.DModel != 384 {
		t.Errorf("d_model = %d; want 384", trm.Config.DModel)
	}
	if trm.Config.NLayers != 2 {
		t.Errorf("n_layers = %d; want 2", trm.Config.NLayers)
	}
	if len(trm.Layers) != 2 {
		t.Errorf("len(Layers) = %d; want 2", len(trm.Layers))
	}
	if len(trm.Probes) != 4 {
		t.Errorf("len(Probes) = %d; want 4", len(trm.Probes))
	}
}

func TestTRMScoresNoLightCone(t *testing.T) {
	weightsPath, referencePath, embeddingsPath := trmTestPaths()
	skipIfMissing(t, weightsPath, referencePath, embeddingsPath)

	trm, err := LoadTRM(weightsPath)
	if err != nil {
		t.Fatalf("LoadTRM: %v", err)
	}

	ref := loadReference(t, referencePath)

	// Load candidate embeddings from the embedding binary.
	// The reference uses candidate_indices [0..63] which are the first 64 embeddings.
	candidateEmbs := loadCandidateEmbeddings(t, embeddingsPath, ref.CandidateIndices)

	// Convert test query to float32.
	queryEmb := f64ToF32(ref.TestQuery)

	// Step with no light cone (fresh state).
	contextVec, newLC := trm.Step(queryEmb, 0, nil) // event_type=0 (query)

	// Verify context vector.
	refContext := f64ToF32(ref.ContextNoLightcone)
	ctxDiff := maxAbsDiff(contextVec, refContext)
	if ctxDiff > 0.01 {
		t.Errorf("context vector (no LC) max diff = %.6f; want < 0.01", ctxDiff)
	}

	// Verify SSM states.
	if len(newLC.States) != len(ref.StatesNoLightcone) {
		t.Fatalf("states count = %d; want %d", len(newLC.States), len(ref.StatesNoLightcone))
	}
	for layerIdx, refState := range ref.StatesNoLightcone {
		goState := newLC.States[layerIdx].H
		refStateF32 := f64ToF32_2D(refState)
		for i := range goState {
			diff := maxAbsDiff(goState[i], refStateF32[i])
			if diff > 0.01 {
				t.Errorf("state[%d][%d] max diff = %.6f; want < 0.01", layerIdx, i, diff)
				break
			}
		}
	}

	// Score candidates.
	scores := trm.ScoreCandidates(contextVec, candidateEmbs)
	refScores := f64ToF32(ref.ScoresNoLightcone)

	scoreDiff := maxAbsDiff(scores, refScores)
	t.Logf("scores (no LC): max diff = %.6f", scoreDiff)
	if scoreDiff > 0.01 {
		t.Errorf("scores (no LC) max diff = %.6f; want < 0.01", scoreDiff)
		// Print first few scores for debugging.
		for i := 0; i < min(5, len(scores)); i++ {
			t.Logf("  score[%d]: go=%.6f ref=%.6f diff=%.6f",
				i, scores[i], refScores[i], math.Abs(float64(scores[i]-refScores[i])))
		}
	}
}

func TestTRMScoresWithLightCone(t *testing.T) {
	weightsPath, referencePath, embeddingsPath := trmTestPaths()
	skipIfMissing(t, weightsPath, referencePath, embeddingsPath)

	trm, err := LoadTRM(weightsPath)
	if err != nil {
		t.Fatalf("LoadTRM: %v", err)
	}

	ref := loadReference(t, referencePath)
	candidateEmbs := loadCandidateEmbeddings(t, embeddingsPath, ref.CandidateIndices)

	// Step 1: Process first event (query) — builds initial light cone.
	queryEmb := f64ToF32(ref.TestQuery)
	_, lc := trm.Step(queryEmb, 0, nil) // event_type=0

	// Step 2: Process second event (retrieval) — uses existing light cone.
	secondEvent := f64ToF32(ref.SecondEvent)
	contextVec, newLC := trm.Step(secondEvent, 1, lc) // event_type=1

	// Verify context vector with light cone.
	refContext := f64ToF32(ref.ContextWithLightcone)
	ctxDiff := maxAbsDiff(contextVec, refContext)
	if ctxDiff > 0.01 {
		t.Errorf("context vector (with LC) max diff = %.6f; want < 0.01", ctxDiff)
	}

	// Verify SSM states after second step.
	if len(newLC.States) != len(ref.StatesWithLightcone) {
		t.Fatalf("states count = %d; want %d", len(newLC.States), len(ref.StatesWithLightcone))
	}

	// Score candidates with light cone context.
	scores := trm.ScoreCandidates(contextVec, candidateEmbs)
	refScores := f64ToF32(ref.ScoresWithLightcone)

	scoreDiff := maxAbsDiff(scores, refScores)
	t.Logf("scores (with LC): max diff = %.6f", scoreDiff)
	if scoreDiff > 0.01 {
		t.Errorf("scores (with LC) max diff = %.6f; want < 0.01", scoreDiff)
		for i := 0; i < min(5, len(scores)); i++ {
			t.Logf("  score[%d]: go=%.6f ref=%.6f diff=%.6f",
				i, scores[i], refScores[i], math.Abs(float64(scores[i]-refScores[i])))
		}
	}
}

func TestTRMScoreRankingPreserved(t *testing.T) {
	weightsPath, referencePath, embeddingsPath := trmTestPaths()
	skipIfMissing(t, weightsPath, referencePath, embeddingsPath)

	trm, err := LoadTRM(weightsPath)
	if err != nil {
		t.Fatalf("LoadTRM: %v", err)
	}

	ref := loadReference(t, referencePath)
	candidateEmbs := loadCandidateEmbeddings(t, embeddingsPath, ref.CandidateIndices)
	queryEmb := f64ToF32(ref.TestQuery)

	contextVec, _ := trm.Step(queryEmb, 0, nil)
	scores := trm.ScoreCandidates(contextVec, candidateEmbs)
	refScores := f64ToF32(ref.ScoresNoLightcone)

	// Check that the top-5 ranking order is preserved.
	goTop5 := topKIndices(scores, 5)
	refTop5 := topKIndices(refScores, 5)

	for i := 0; i < 5 && i < len(goTop5) && i < len(refTop5); i++ {
		if goTop5[i] != refTop5[i] {
			t.Errorf("rank %d: go=%d ref=%d (score go=%.4f ref=%.4f)",
				i, goTop5[i], refTop5[i], scores[goTop5[i]], refScores[refTop5[i]])
		}
	}
}

func TestLightConeNorms(t *testing.T) {
	weightsPath, referencePath, _ := trmTestPaths()
	skipIfMissing(t, weightsPath, referencePath)

	trm, err := LoadTRM(weightsPath)
	if err != nil {
		t.Fatalf("LoadTRM: %v", err)
	}

	ref := loadReference(t, referencePath)
	queryEmb := f64ToF32(ref.TestQuery)
	_, lc := trm.Step(queryEmb, 0, nil)

	norms, compressed := trm.GetLightConeNorms(lc)
	if len(norms) != 2 {
		t.Fatalf("norms len = %d; want 2", len(norms))
	}
	if compressed <= 0 {
		t.Error("compressed norm should be > 0 for a non-zero light cone")
	}
	for i, n := range norms {
		if n <= 0 {
			t.Errorf("norm[%d] = %f; want > 0", i, n)
		}
	}

	// Nil light cone should return zero norms.
	nilNorms, nilCompressed := trm.GetLightConeNorms(nil)
	if nilNorms != nil || nilCompressed != 0 {
		t.Error("nil light cone should return nil norms and 0 compressed")
	}
}

// ── helpers ──────────────────────────────────────────────────────────────────

func loadReference(t *testing.T, path string) trmReferenceData {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read reference: %v", err)
	}
	var ref trmReferenceData
	if err := json.Unmarshal(data, &ref); err != nil {
		t.Fatalf("unmarshal reference: %v", err)
	}
	return ref
}

// loadCandidateEmbeddings loads specific embeddings from the EMB1 binary file.
func loadCandidateEmbeddings(t *testing.T, embPath string, indices []int) [][]float32 {
	t.Helper()

	// We need to read the embeddings file to extract specific indices.
	// Use a minimal reader since we only need a few rows.
	f, err := os.Open(embPath)
	if err != nil {
		t.Fatalf("open embeddings: %v", err)
	}
	defer f.Close()

	// Read EMB1 header.
	magic := make([]byte, 4)
	if _, err := f.Read(magic); err != nil {
		t.Fatalf("read magic: %v", err)
	}
	if string(magic) != "EMB1" {
		t.Fatalf("bad magic: %q", string(magic))
	}

	var nChunks, dim uint32
	buf := make([]byte, 4)
	if _, err := f.Read(buf); err != nil {
		t.Fatalf("read nChunks: %v", err)
	}
	nChunks = uint32(buf[0]) | uint32(buf[1])<<8 | uint32(buf[2])<<16 | uint32(buf[3])<<24
	if _, err := f.Read(buf); err != nil {
		t.Fatalf("read dim: %v", err)
	}
	dim = uint32(buf[0]) | uint32(buf[1])<<8 | uint32(buf[2])<<16 | uint32(buf[3])<<24

	_ = nChunks // we trust the indices are in range

	// Read the full embedding data. For test files this is small enough.
	headerSize := int64(4 + 4 + 4) // magic + nChunks + dim
	_ = headerSize

	// Read all embeddings at once.
	rowBytes := int(dim) * 4
	result := make([][]float32, len(indices))

	for i, idx := range indices {
		offset := int64(12) + int64(idx)*int64(rowBytes) // 12 = header size
		row := make([]byte, rowBytes)
		if _, err := f.ReadAt(row, offset); err != nil {
			t.Fatalf("read embedding[%d]: %v", idx, err)
		}
		emb := make([]float32, dim)
		for j := 0; j < int(dim); j++ {
			bits := uint32(row[j*4]) | uint32(row[j*4+1])<<8 | uint32(row[j*4+2])<<16 | uint32(row[j*4+3])<<24
			emb[j] = math.Float32frombits(bits)
		}
		result[i] = emb
	}

	return result
}

// topKIndices returns the indices of the top-K highest values.
func topKIndices(scores []float32, k int) []int {
	type scored struct {
		idx   int
		score float32
	}
	items := make([]scored, len(scores))
	for i, s := range scores {
		items[i] = scored{idx: i, score: s}
	}
	// Sort descending.
	for i := 0; i < len(items); i++ {
		for j := i + 1; j < len(items); j++ {
			if items[j].score > items[i].score {
				items[i], items[j] = items[j], items[i]
			}
		}
	}
	if k > len(items) {
		k = len(items)
	}
	result := make([]int, k)
	for i := 0; i < k; i++ {
		result[i] = items[i].idx
	}
	return result
}
