// spine_render.go — render the decision manifold into its projected artifact
// (decision-lineage.md) and into the human-facing `cog spine` views.
//
// Both surfaces read the same *Manifold so the projection file on disk and the
// live CLI output never diverge.
package engine

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// renderDecisionLineageProjection renders the full decision-lineage projection
// markdown: the centre of mass, the gravity ranking, the inertia field, the
// accretion eras, and the orbital basins. This is the generated artifact the
// reconciler writes to projections/decision-lineage.md.
func renderDecisionLineageProjection(m *Manifold) string {
	var b strings.Builder

	b.WriteString("# Decision Lineage — The Spine Manifold\n\n")
	b.WriteString("_Generated by DecisionLineageReconciler — do not edit by hand._\n\n")
	b.WriteString(fmt.Sprintf("_Last generated: %s_\n\n", m.ComputedAt.Format(time.RFC3339)))
	b.WriteString("The gravity / inertia field over the architecture's own decisions ")
	b.WriteString("(ADRs, RFCs, ratified decision-insights and their `rel:` edges). ")
	b.WriteString("Gravity = weighted in-degree (centre of mass). ")
	b.WriteString("Inertia = settledness (age × low-revisit × cost-to-move). ")
	b.WriteString("Accretion = decisions ordered by date. ")
	b.WriteString("Orbits = clustering by edge-proximity to the high-mass cores.\n\n")
	b.WriteString(fmt.Sprintf("Corpus: **%d decisions**.\n\n", len(m.Vertebrae)))

	// ── Centre of mass ──
	b.WriteString("## Centre of Mass\n\n")
	if len(m.Cores) == 0 {
		b.WriteString("_(No decisions carry incoming gravity yet — the field is flat.)_\n\n")
	} else {
		b.WriteString("The highest-gravity vertebrae — the stars the rest of the corpus orbits:\n\n")
		b.WriteString("| Gravity | Vertebra | Kind | Status | Inertia | Cost-to-move |\n")
		b.WriteString("|--:|---|---|---|--:|--:|\n")
		for _, c := range m.Cores {
			b.WriteString(fmt.Sprintf("| %.1f | `%s` | %s | %s | %.2f | %d |\n",
				c.Gravity, c.Decision.ID, dashIfEmpty(c.Decision.Kind),
				dashIfEmpty(c.Decision.Status), c.Inertia, c.CostToMove))
		}
		b.WriteString("\n")
	}

	// ── Gravity ranking ──
	b.WriteString("## Gravity Ranking (top vertebrae by weighted in-degree)\n\n")
	topN := m.Ranked
	const rankLimit = 25
	if len(topN) > rankLimit {
		topN = topN[:rankLimit]
	}
	wrote := false
	for _, v := range topN {
		if v.Gravity <= 0 {
			continue
		}
		wrote = true
		b.WriteString(fmt.Sprintf("- **%.1f** `%s` — %s (in:%d, out:%d)\n",
			v.Gravity, v.Decision.ID, titleOrID(v.Decision), v.RawInDegree, v.OutDegree))
	}
	if !wrote {
		b.WriteString("_(No incoming edges resolved within the corpus yet.)_\n")
	}
	b.WriteString("\n")

	// ── Inertia field ──
	b.WriteString("## Inertia Field — what is settled, what is molten\n\n")
	settled, molten := partitionByInertia(m)
	b.WriteString("**Settled core (high inertia — old, sealed, depended-on):**\n\n")
	if len(settled) == 0 {
		b.WriteString("_(none)_\n")
	} else {
		for _, v := range settled {
			b.WriteString(fmt.Sprintf("- `%s` (inertia %.2f, status %s, age %dd)\n",
				v.Decision.ID, v.Inertia, dashIfEmpty(v.Decision.Status), v.AgeDays))
		}
	}
	b.WriteString("\n**Molten / proto-planetary (low inertia — draft / proposed / young):**\n\n")
	if len(molten) == 0 {
		b.WriteString("_(none)_\n")
	} else {
		for _, v := range molten {
			b.WriteString(fmt.Sprintf("- `%s` (inertia %.2f, status %s)\n",
				v.Decision.ID, v.Inertia, dashIfEmpty(v.Decision.Status)))
		}
	}
	b.WriteString("\n")

	// ── Accretion ──
	b.WriteString("## Accretion Over Time\n\n")
	b.WriteString("Decisions ordered by the era they formed in — the core forming first, ")
	b.WriteString("later bodies accreting around existing wells:\n\n")
	for _, era := range m.Eras {
		b.WriteString(fmt.Sprintf("### %s — %d decisions, mass %.1f\n\n", era.Label, len(era.Decisions), era.TotalMass))
		for _, id := range era.Decisions {
			v := m.Vertebrae[id]
			b.WriteString(fmt.Sprintf("- `%s` (gravity %.1f)\n", id, v.Gravity))
		}
		b.WriteString("\n")
	}

	// ── Orbits ──
	b.WriteString("## Orbits / Basins\n\n")
	b.WriteString("Which bodies orbit which well (clustered by structural edge-proximity to a core):\n\n")
	for _, c := range m.Cores {
		orbiters := m.Orbiters(c.Decision.ID)
		b.WriteString(fmt.Sprintf("### Well: `%s` (gravity %.1f) — %d orbiting bodies\n\n",
			c.Decision.ID, c.Gravity, len(orbiters)))
		if len(orbiters) == 0 {
			b.WriteString("_(no bodies orbit this well yet)_\n\n")
			continue
		}
		for _, id := range orbiters {
			v := m.Vertebrae[id]
			b.WriteString(fmt.Sprintf("- `%s` (gravity %.1f)\n", id, v.Gravity))
		}
		b.WriteString("\n")
	}

	// Free bodies: basins keyed by a non-core id.
	free := freeBodies(m)
	if len(free) > 0 {
		b.WriteString("### Free bodies (no core attachment)\n\n")
		for _, id := range free {
			b.WriteString(fmt.Sprintf("- `%s`\n", id))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// ─── CLI views (text) ─────────────────────────────────────────────────────────

// renderSpineOverview produces the `cog spine` overview text: centre of mass,
// top vertebrae, basins, and accretion eras.
func renderSpineOverview(m *Manifold) string {
	var b strings.Builder
	b.WriteString("THE SPINE — decision manifold\n")
	b.WriteString(strings.Repeat("=", 60) + "\n")
	b.WriteString(fmt.Sprintf("%d decisions, computed %s\n\n", len(m.Vertebrae), m.ComputedAt.Format("2006-01-02 15:04 MST")))

	b.WriteString("CENTRE OF MASS (top vertebrae by gravity)\n")
	b.WriteString(strings.Repeat("-", 60) + "\n")
	if len(m.Cores) == 0 {
		b.WriteString("  (the field is flat — no incoming gravity yet)\n")
	}
	for i, c := range m.Cores {
		b.WriteString(fmt.Sprintf("  %d. %-40s  g=%.1f  inertia=%.2f\n",
			i+1, truncateID(c.Decision.ID, 40), c.Gravity, c.Inertia))
	}
	b.WriteString("\n")

	b.WriteString("BASINS (which bodies orbit which well)\n")
	b.WriteString(strings.Repeat("-", 60) + "\n")
	for _, c := range m.Cores {
		orbiters := m.Orbiters(c.Decision.ID)
		b.WriteString(fmt.Sprintf("  %s  (g=%.1f, %d orbiting)\n", c.Decision.ID, c.Gravity, len(orbiters)))
	}
	b.WriteString("\n")

	b.WriteString("ACCRETION ERAS (oldest first)\n")
	b.WriteString(strings.Repeat("-", 60) + "\n")
	for _, era := range m.Eras {
		b.WriteString(fmt.Sprintf("  %-28s  %3d decisions  mass=%.1f\n",
			era.Label, len(era.Decisions), era.TotalMass))
	}
	b.WriteString("\n")
	b.WriteString("Run `cog spine <id>` for one decision, `cog spine --orbits`,\n")
	b.WriteString("`cog spine --accretion`, or add `--json` for machine-readable output.\n")
	return b.String()
}

// renderSpineDecision produces the `cog spine <id>` detail text for one vertebra.
func renderSpineDecision(m *Manifold, v *VertebraMetrics) string {
	var b strings.Builder
	d := v.Decision
	b.WriteString(fmt.Sprintf("VERTEBRA: %s\n", d.ID))
	b.WriteString(strings.Repeat("=", 60) + "\n")
	if d.Title != "" {
		b.WriteString(fmt.Sprintf("  title:    %s\n", d.Title))
	}
	b.WriteString(fmt.Sprintf("  kind:     %s\n", dashIfEmpty(d.Kind)))
	b.WriteString(fmt.Sprintf("  status:   %s\n", dashIfEmpty(d.Status)))
	b.WriteString(fmt.Sprintf("  created:  %s (age %dd)\n", dashIfEmpty(d.Created), v.AgeDays))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("  GRAVITY:        %.1f  (weighted in-degree; raw in=%d)\n", v.Gravity, v.RawInDegree))
	b.WriteString(fmt.Sprintf("  INERTIA:        %.2f  (settledness 0..1)\n", v.Inertia))
	b.WriteString(fmt.Sprintf("  COST-TO-MOVE:   %d   (structural dependents that would move with it)\n", v.CostToMove))
	b.WriteString(fmt.Sprintf("  OUT-DEGREE:     %d\n", v.OutDegree))
	if v.Basin == d.ID {
		b.WriteString("  BASIN:          (self — this is a core, or a free body)\n")
	} else {
		b.WriteString(fmt.Sprintf("  BASIN:          orbits `%s`\n", v.Basin))
	}
	b.WriteString("\n")

	b.WriteString("OUTGOING EDGES (what this decision pulls on)\n")
	b.WriteString(strings.Repeat("-", 60) + "\n")
	if len(d.Edges) == 0 {
		b.WriteString("  (none)\n")
	}
	edges := append([]DecisionEdge(nil), d.Edges...)
	sort.Slice(edges, func(i, j int) bool {
		if edges[i].Rel != edges[j].Rel {
			return edges[i].Rel < edges[j].Rel
		}
		return edges[i].Target < edges[j].Target
	})
	for _, e := range edges {
		marker := " "
		if isStructuralEdge(e.Rel) {
			marker = "*"
		}
		b.WriteString(fmt.Sprintf("  %s %-16s → %s\n", marker, e.Rel, e.Target))
	}
	b.WriteString("\n")

	in := m.IncomingEdges(d.ID)
	b.WriteString(fmt.Sprintf("INCOMING EDGES (what pulls on this decision) — %d\n", len(in)))
	b.WriteString(strings.Repeat("-", 60) + "\n")
	if len(in) == 0 {
		b.WriteString("  (none)\n")
	}
	for _, e := range in {
		marker := " "
		if isStructuralEdge(e.Rel) {
			marker = "*"
		}
		b.WriteString(fmt.Sprintf("  %s %-16s ← %s\n", marker, e.Rel, e.Target))
	}
	b.WriteString("\n  (* = spine-structural / lineage edge; others are annotation edges)\n")
	return b.String()
}

// renderSpineOrbits produces the `cog spine --orbits` view: full basin membership.
func renderSpineOrbits(m *Manifold) string {
	var b strings.Builder
	b.WriteString("ORBITAL BASINS\n")
	b.WriteString(strings.Repeat("=", 60) + "\n\n")
	for _, c := range m.Cores {
		orbiters := m.Orbiters(c.Decision.ID)
		b.WriteString(fmt.Sprintf("WELL: %s  (gravity %.1f, %d orbiting)\n", c.Decision.ID, c.Gravity, len(orbiters)))
		for _, id := range orbiters {
			b.WriteString(fmt.Sprintf("    %-44s g=%.1f\n", truncateID(id, 44), m.Vertebrae[id].Gravity))
		}
		b.WriteString("\n")
	}
	free := freeBodies(m)
	if len(free) > 0 {
		b.WriteString("FREE BODIES (no core attachment)\n")
		for _, id := range free {
			b.WriteString(fmt.Sprintf("    %s\n", id))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// renderSpineAccretion produces the `cog spine --accretion` view: the timeline.
func renderSpineAccretion(m *Manifold) string {
	var b strings.Builder
	b.WriteString("ACCRETION TIMELINE — the core forms first, bodies accrete around it\n")
	b.WriteString(strings.Repeat("=", 60) + "\n\n")
	for _, era := range m.Eras {
		b.WriteString(fmt.Sprintf("%s   (%d decisions, mass %.1f)\n", era.Label, len(era.Decisions), era.TotalMass))
		for _, id := range era.Decisions {
			v := m.Vertebrae[id]
			b.WriteString(fmt.Sprintf("    %-44s g=%.1f\n", truncateID(id, 44), v.Gravity))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// ─── render helpers ─────────────────────────────────────────────────────────

// partitionByInertia splits vertebrae into the settled core (inertia >= 0.7)
// and the molten layer (inertia < 0.35), each gravity-desc, capped for brevity.
func partitionByInertia(m *Manifold) (settled, molten []*VertebraMetrics) {
	for _, v := range m.Ranked {
		switch {
		case v.Inertia >= 0.7:
			settled = append(settled, v)
		case v.Inertia < 0.35:
			molten = append(molten, v)
		}
	}
	const cap = 15
	if len(settled) > cap {
		settled = settled[:cap]
	}
	if len(molten) > cap {
		molten = molten[:cap]
	}
	return settled, molten
}

// freeBodies returns the ids of vertebrae whose basin is themselves but that
// are not cores — i.e. unattached free bodies — sorted for determinism.
func freeBodies(m *Manifold) []string {
	coreSet := make(map[string]bool, len(m.Cores))
	for _, c := range m.Cores {
		coreSet[c.Decision.ID] = true
	}
	var free []string
	for _, v := range m.Ranked {
		if v.Basin == v.Decision.ID && !coreSet[v.Decision.ID] {
			free = append(free, v.Decision.ID)
		}
	}
	sort.Strings(free)
	return free
}

func dashIfEmpty(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return s
}

func titleOrID(d Decision) string {
	if strings.TrimSpace(d.Title) != "" {
		return d.Title
	}
	return d.ID
}

func truncateID(s string, n int) string {
	if len(s) <= n {
		return s
	}
	if n <= 1 {
		return s[:n]
	}
	return s[:n-1] + "…"
}
